export type PartnerFocus = "industrie" | "campus" | "collectif";

export type PartnerProfile = {
  id: string;
  name: string;
  type: string;
  focus: PartnerFocus;
  tagline: string;
  pledge: string;
  action: string;
  region: string;
  color: string;
  impact: number; // 0-100 scale for playful progress bar
  signals: string[];
  allies: string[];
};

export const partners: PartnerProfile[] = [
  {
    id: "viveris",
    name: "Viveris",
    type: "Entreprise tech responsable",
    focus: "industrie",
    tagline: "Audit les architectures pour traquer les octets inutiles.",
    pledge: "Publier des kits d'autodiagnostic pour les lycees et IUT.",
    action: "Organiser un sprint sobriete avec leur cellule GreenOps.",
    region: "Paris / Toulouse",
    color: "#f96fb0",
    impact: 82,
    signals: ["Cartographie CO2 des microservices", "Coachs cloud frugaux", "Budget d'innovation partage"],
    allies: ["sfeir", "capgemini"],
  },
  {
    id: "riministreet",
    name: "Rimini Street",
    type: "Support logiciel",
    focus: "industrie",
    tagline: "Allonge la vie des ERP, evite les migrations carbonnees.",
    pledge: "Financer un observatoire open data sur la dette logicielle des campus.",
    action: "Inviter Rimini a dissequer un vieux SI avec les etudiants.",
    region: "Europe",
    color: "#ff9f67",
    impact: 74,
    signals: ["Reverse engineering pedagogique", "Contrats mutualises", "Ateliers de retro-documentation"],
    allies: ["soprasteria", "capcod"],
  },
  {
    id: "uge",
    name: "Universite Gustave Eiffel (IUT Marne)",
    type: "Campus",
    focus: "campus",
    tagline: "Fabrique des inventaires numeriques comme on recense les materiaux.",
    pledge: "Partager ses scripts d'analyse d'empreinte aux autres IUT.",
    action: "Monter un atelier Fresque des serveurs avec leurs etudiants.",
    region: "Marne-la-Vallee",
    color: "#8de36a",
    impact: 68,
    signals: ["Parc mutualise open source", "Laboratoire low-tech", "Residences d'artistes reparateurs"],
    allies: ["iut-info", "universite-bordeaux"],
  },
  {
    id: "iut-info",
    name: "IUT Departements Informatiques",
    type: "Reseau campus",
    focus: "campus",
    tagline: "Enseignent la sobriete par le code et par les usages.",
    pledge: "Publier un tronc commun DUT Sobriete accessible a toutes les filieres.",
    action: "Echanger un jeu de TD sur la reduction des requetes.",
    region: "France",
    color: "#6bc4ff",
    impact: 71,
    signals: ["TP de profilage energetique", "Serveurs en don libre", "Pair-programming inter-IUT"],
    allies: ["uge", "cesi"],
  },
  {
    id: "sfeir",
    name: "SFEIR",
    type: "Collectif d'expertes",
    focus: "industrie",
    tagline: "Met en scene des design sprints sobrietaires.",
    pledge: "Ouvrir sa bibliotheque de composants low-carbon.",
    action: "Co-concevoir un module front eco avec eux.",
    region: "Remote / Lille",
    color: "#ffd369",
    impact: 79,
    signals: ["Guidelines d'accessibilite energetique", "Mentorat dev durable", "Audit UX vs Watt"],
    allies: ["viveris", "capgemini"],
  },
  {
    id: "capcod",
    name: "Capcod",
    type: "Agence de communs",
    focus: "collectif",
    tagline: "Anime des ateliers d'appropriation des infrastructures numeriques.",
    pledge: "Documenter en creative commons leurs scenarii de gouvernance.",
    action: "Inviter Capcod pour cartographier votre SI reel.",
    region: "Occitanie",
    color: "#c792ea",
    impact: 66,
    signals: ["Serious games sur la decentralisation", "Cartes de flux low-tech", "Formation aux communs"],
    allies: ["neverhack", "radio-occitania"],
  },
  {
    id: "alluco",
    name: "Alluco",
    type: "Tiers-lieu metal et low-tech",
    focus: "collectif",
    tagline: "Transforme les chassis obsoletes en postes de labo.",
    pledge: "Ajouter un manuel open hardware pour les ecoles.",
    action: "Programmer une session de depose-reutilisation.",
    region: "Nouvelle-Aquitaine",
    color: "#ff87ab",
    impact: 58,
    signals: ["Fablab itinerant", "Reparation festive", "Bricolage energetique"],
    allies: ["aedi", "utopie3d"],
  },
  {
    id: "fst",
    name: "Faculte des Sciences et Techniques",
    type: "Campus",
    focus: "campus",
    tagline: "Croise recherche, enseignement et chantiers low-tech.",
    pledge: "Partager ses protocoles d'instrumentation energie.",
    action: "Tester leurs kits de mesure en continu.",
    region: "Nouvelle-Aquitaine",
    color: "#6bf2c1",
    impact: 64,
    signals: ["Capteurs open hardware", "Observatoire d'usage", "Seminaire sciences sociales"],
    allies: ["universite-bordeaux", "esa-tech"],
  },
  {
    id: "soprasteria",
    name: "Sopra Steria",
    type: "Entreprise de services",
    focus: "industrie",
    tagline: "Industrialise les feuilles de route Green IT pour les grands reseaux.",
    pledge: "Mettre a dispo ses simulateurs d'impact carbone.",
    action: "Coacher les promos sur la gouvernance data frugale.",
    region: "Europe",
    color: "#ff6f91",
    impact: 77,
    signals: ["GreenOps dans grands comptes", "Programme de reconversion", "MOOC gouvernance"],
    allies: ["capgemini", "riministreet"],
  },
  {
    id: "cesi",
    name: "CESI ecoles d'ingenieurs",
    type: "Campus",
    focus: "campus",
    tagline: "Teste des maquettes de villes sobres avec ses etudiants.",
    pledge: "Rendre accessibles leurs chaines pedagogiques.",
    action: "Echanger un module learning expedition low-tech.",
    region: "France",
    color: "#7dd3ff",
    impact: 63,
    signals: ["Learning labs hybrides", "Hackathons sur l'usage", "Echanges internationaux"],
    allies: ["iut-info", "universite-bordeaux"],
  },
  {
    id: "aedi",
    name: "AEDI",
    type: "Association etudiante",
    focus: "collectif",
    tagline: "Met les collectifs d'etudiants en reseau pour agir sur leurs campus.",
    pledge: "Publier leurs kits de mobilisation en creative commons.",
    action: "Inviter AEDI a coacher votre crew etudiant.",
    region: "France",
    color: "#ffa94d",
    impact: 57,
    signals: ["Hotline mobilisation", "Partage de budgets", "Carnet de campagnes"],
    allies: ["ajir", "radio-occitania"],
  },
  {
    id: "neverhack",
    name: "NEVERHACK",
    type: "Collectif cyber",
    focus: "collectif",
    tagline: "Hacke les habitudes pour securiser sans surconsommer.",
    pledge: "Ouvrir leur parcours hygiene numerique a toutes les ecoles.",
    action: "Construire un raid red-team pedagogique.",
    region: "Occitanie",
    color: "#b388ff",
    impact: 61,
    signals: ["Ateliers d'opsec low-tech", "Protocoles open source", "Culture du doute"],
    allies: ["capcod", "utopie3d"],
  },
  {
    id: "esa-tech",
    name: "ESA Tech",
    type: "Ecole",
    focus: "campus",
    tagline: "Relie agro-ecologie et numerique frugal.",
    pledge: "Documenter leurs fermes connectees sobres.",
    action: "Visiter leurs essais de pilotage low data.",
    region: "Angers",
    color: "#93e0ff",
    impact: 59,
    signals: ["Capteurs passifs", "Gouvernance paysanne", "Stages longue duree"],
    allies: ["fst", "universite-bordeaux"],
  },
  {
    id: "radio-occitania",
    name: "Radio Occitania",
    type: "Media associatif",
    focus: "collectif",
    tagline: "Diffuse les recits de sobriete joyful.",
    pledge: "Offrir des chroniques Nous ne sommes pas condamnes aux campus.",
    action: "Monter un plateau radio lors de vos portes ouvertes.",
    region: "Occitanie",
    color: "#ffcad4",
    impact: 52,
    signals: ["Studios mobiles", "Podcast open license", "Banque sonore"],
    allies: ["aedi", "capcod"],
  },
  {
    id: "a14good",
    name: "A14GOOD",
    type: "Entreprise a mission",
    focus: "industrie",
    tagline: "Optimise les achats pour privilegier le reemploi.",
    pledge: "Donner acces a son referentiel fournisseurs circulaires.",
    action: "Verifier votre prochaine consultation avec eux.",
    region: "Paris",
    color: "#ffb347",
    impact: 69,
    signals: ["Marketplace circulaire", "Scorecards sobriete", "Coaching achats"],
    allies: ["viveris", "capgemini"],
  },
  {
    id: "ajir",
    name: "AJIR",
    type: "Jeunes ambassadeurs",
    focus: "collectif",
    tagline: "Fait dialoguer les generations de dirigeantes.",
    pledge: "Partager leurs parcours d'engagement a toutes les promos.",
    action: "Organiser un speed meeting AJIR x campus.",
    region: "Nouvelle-Aquitaine",
    color: "#fb7185",
    impact: 55,
    signals: ["Mentorat pair", "Plateforme de pitch", "Parcours diplomatique"],
    allies: ["aedi", "radio-occitania"],
  },
  {
    id: "overcode",
    name: "OVERCODE Mauritanie",
    type: "Fabrique africaine",
    focus: "campus",
    tagline: "Code pour la souverainete africaine avec peu de ressources.",
    pledge: "Co-ecrire des modules communs francophonie.",
    action: "Organiser un jumelage de promotions.",
    region: "Nouakchott",
    color: "#50f0b2",
    impact: 67,
    signals: ["Kits satellites open source", "Plateforme echanges", "Fablab solaire"],
    allies: ["universite-bordeaux", "iut-info"],
  },
  {
    id: "universite-bordeaux",
    name: "Universite de Bordeaux",
    type: "Campus pivot",
    focus: "campus",
    tagline: "Base arriere de l'NDI: recherche, experimentation, partage.",
    pledge: "Publier ses learnings sur les low data campus.",
    action: "Venir voir le demonstrateur Rafistole IRL.",
    region: "Bordeaux",
    color: "#9d8bff",
    impact: 88,
    signals: ["Living lab sobriete", "Plateforme open science", "Gouvernance partagee"],
    allies: ["fst", "utopie3d"],
  },
  {
    id: "arited",
    name: "ARITED",
    type: "Reseau d'enseignant.es",
    focus: "collectif",
    tagline: "Mutualise ressources pedagogiques et retours d'experience.",
    pledge: "Libere ses plans de cours sous licence ouverte.",
    action: "Proposer un micro cours Rafistole dans leur reseau.",
    region: "France",
    color: "#ff88e8",
    impact: 60,
    signals: ["Bibliotheque creative commons", "Cliniques pedagogiques", "MOOC en commun"],
    allies: ["iut-info", "cesi"],
  },
  {
    id: "utopie3d",
    name: "UTOPIE 3D",
    type: "Lab speculative",
    focus: "collectif",
    tagline: "Imagine des dispositifs physiques pour visualiser les flux.",
    pledge: "Co-fabriquer des sculptures pedagogiques.",
    action: "Integrer une installation UTOPIE 3D a votre hall.",
    region: "Bordeaux",
    color: "#36f1cd",
    impact: 62,
    signals: ["Data viz tangible", "Residences artistiques", "Ateliers d'ecriture"],
    allies: ["neverhack", "universite-bordeaux"],
  },
  {
    id: "klub",
    name: "KLUB",
    type: "Studio de design",
    focus: "industrie",
    tagline: "Met en musique les interfaces qui donnent envie de sobriete.",
    pledge: "Partager ses patrons d'animation low GPU.",
    action: "Designer votre prochain atelier avec KLUB.",
    region: "Paris",
    color: "#ffa8ff",
    impact: 65,
    signals: ["Design systems modulaires", "Tests utilisateurs fun", "Formations story"],
    allies: ["sfeir", "capcod"],
  },
  {
    id: "capgemini",
    name: "Capgemini",
    type: "Entreprise de services",
    focus: "industrie",
    tagline: "Scale les feuilles de route Net Zero des institutions.",
    pledge: "Mettre ses simulateurs de maturite a dispo des campus.",
    action: "Challenger votre plan neutralite avec eux.",
    region: "Monde",
    color: "#00d2ff",
    impact: 83,
    signals: ["Centres d'excellence Green IT", "Programme Architectes du low code", "Chaires academiques"],
    allies: ["soprasteria", "a14good"],
  },
];

export const partnerFilters = [
  { id: "all", label: "Tout le monde" },
  { id: "campus", label: "Campus" },
  { id: "industrie", label: "Entreprises" },
  { id: "collectif", label: "Collectifs" },
] as const;

export type PartnerFilterId = (typeof partnerFilters)[number]["id"];
